### ISSUE TITLE
Download Failed - Forbidden

### ISSUE THREAD

**Issue by j-duvall** [corbindavenport/noplugin#2]
Hi,

I am seeing an issue with noplugin where it will not download a quicktime .mov file.  When I click "Open Content," the download says "Failed - Forbidden."  Here is the specific web page where I am seeing this:

http://kmoddl.library.cornell.edu/resources.php?id=213

I have checked that the movie is available there.  It opens correctly in a Quicktime plugin using IE11.

All of the movies hosted on the Cornell KMODDL site seem to have the same issue.

http://kmoddl.library.cornell.edu/model.php?m=109

james

**Comment by corbindavenport** [comment]
This is caused by the web server server blocking downloads of a file, I'm looking into ways around this but I'm not sure if it's possible. Even when I manually download the link in Chrome with 'Save As...' I get the same error.

**Comment by j-duvall** [comment]
Thanks for looking in to this and responding so quickly.

Yes, my first thought was that the site is blocking the download.  I've contacted the webmaster at Cornell's KMODDL, but no response.  Somehow, the file is available for the QuickTime plugin to access, but not available for regular download.  It would be helpful if the noplugin extension could use some form of stream capturing to download the file anyway.  I suppose it is possible that Cornell is trying to actively block downloading for copyright reasons, but I suspect that they are just using the default setup for quicktime.  It seems to block downloading most of the time.

**Comment by corbindavenport** [comment]
Copyright seems likely, I'm looking into Chrome's API docs but so far I'm not seeing a way to change the download from a simple download to something that emulates the streaming that plugins use. https://developer.chrome.com/extensions/downloads
