### ISSUE TITLE
Doesn't work on http://3dtopo.com/lostPLA/

### ISSUE THREAD

**Issue by grndkntrl** [corbindavenport/noplugin#3]
Hi Corbin, There's 4 .mov videos on http://3dtopo.com/lostPLA/ (two near the top & two at the end of the page) which are not being picked up by noplugin. I just get Chrome's "This plugin is not supported" as though it is still trying to load Apple's plugin instead of using your extension.

I don't have quicktime installed on my machine (Win 7 x64 Ultimate) anyway so it's not like chrome is trying/able to load Apple's plugin locally.

Any idea what's up?

**Comment by corbindavenport** [comment]
The video is being loaded dynamically (after page load), and I think NoPlugin only searches embeds on page load. Will look into it.

**Comment by corbindavenport** [comment]
Looks like the page has been removed. Closing the issue for now.
