### ISSUE TITLE
There is a styling with enforcing height and width in Chrome

### ISSUE THREAD

**Issue by chaucerling** [corbindavenport/noplugin#30]
http://yanaginagi.net/disco/?p=591

screenshot
<img width="227" alt="2018-01-06 00 01 03" src="https://user-images.githubusercontent.com/6396793/34617131-5671db56-f275-11e7-8803-70ab9775edfe.png">
<img width="394" alt="2018-01-06 00 01 08" src="https://user-images.githubusercontent.com/6396793/34617133-57042f42-f275-11e7-980e-434c58cf463b.png">

**Comment by corbindavenport** [comment]
This should be fixed now.
