### ISSUE TITLE
Add Flash Player support

### ISSUE THREAD

**Issue by corbindavenport** [corbindavenport/noplugin#37]
NoPlugin should detect if Flash player is currently active in the browser, and if it's not running, then NoPlugin can take over. Some options for opening Flash content:

- Detect Flash videos and offer to play them in VLC
- On Windows, tell the user to open the current URL in Internet Explorer, maybe using a [prompt](https://www.w3schools.com/js/js_popup.asp) with the URL in the text field for easy copying
- Try to load the object with [Shumway](https://github.com/mozilla/shumway) (with warning that it probably won't work)

**Comment by Madis0** [comment]
Another option would be using the [Flash Projector](https://www.adobe.com/support/flashplayer/debug_downloads.html), which is browser-independent, cross-platform and officially updated (until deprecated, I guess).

**Comment by corbindavenport** [comment]
Yeah, that would probably be the best method for games and other fully-contained embedded SWFs. I wonder if there's a URL scheme to automatically open a URL in Flash Projector, or if NoPlugin will have to download it and walk the user through opening it, like it has to do for regular video files.

**Comment by corbindavenport** [comment]
I was worried that any parameters set in the HTML wouldn't work in Flash Projector, but it looks like Flash Projector does accept parameters: https://stackoverflow.com/a/3303871/2255592

So the best solution would be for NoPlugin to process all the parameters, create a new URL with all of them added in, and then walk the user through opening Flash Projector and pasting the URL in. Not super ideal, but it doesn't look like there's a url scheme for Flash Projector (like `rtsp://` for livestreams), and it *should* still keep everything functional.

**Comment by corbindavenport** [comment]
Actually, it seems like parameters and variables are two different things in Flash:

https://www.permadi.com/tutorial/flashVars/index.html
https://helpx.adobe.com/flash/kb/flash-object-embed-tag-attributes.html

**Comment by corbindavenport** [comment]
NoPlugin now has initial Flash Player support in v6.0: https://blog.corbin.io/post/189323101589/noplugin-60-is-out

Stuff that still needs to be implemented:

- Compatibility mode that gets around JavaScript-based Flash detection (#46)
- Passing parameters/variables in URL to Flash Projector, where possible

**Comment by corbindavenport** [comment]
Flash variables now working on v6.2 dev branch:

![Screenshot from 2020-01-18 17-02-33](https://user-images.githubusercontent.com/3879063/72671183-81d1f900-3a14-11ea-8844-a5b1b9a382be.png)

**Comment by corbindavenport** [comment]
Merging this into #46, since the only work left here is to add an option to spoof Flash being installed.
