### ISSUE TITLE
audio content cannot be played

### ISSUE THREAD

**Issue by etsypin** [corbindavenport/noplugin#4]
NoPlugin cannot play audio content on this webpage: 

http://www.rtr.spb.ru/Radio_ru/First_Person/news_detail_v.asp?id=14007

**Comment by corbindavenport** [comment]
Works on my machine with Chrome 54 and NoPlugin 2.2. What operating system are you using?

**Comment by etsypin** [comment]
Windows XP.

**Comment by corbindavenport** [comment]
Can you test on NoPlugin 3.0? Does it have the same issue?

**Comment by etsypin** [comment]
Re: [corbindavenport/noplugin] audio content cannot be played (#4)



Hello, Corbin.

On January 24, 2017, 4:13:54 you wrote:



> Can you test on NoPlugin 3.0? Does it have the same issue?


It loads but the play button is unclickable.


-- 
Yours, 
 Eugene                          mailto:eugene.tsypin@mail.ru

**Comment by corbindavenport** [comment]
It looks like the site has moved to using Flash player. I'm closing this issue for now, if you still have problems with this page, feel free to re-open it and leave a comment.
