### ISSUE TITLE
Add support for different embed types

### ISSUE THREAD

**Issue by llacb47** [corbindavenport/noplugin#61]
On this page `http://personal.psu.edu/staff/d/r/drs18/XHTMLVideo/` there are several different types of embeds. In IE with plugins, all of them play correctly.  With NoPlugin, only the first plays correctly. Support should be added for all of these embed types in NoPlugin.

**Comment by corbindavenport** [comment]
Weird, the videos are wrapped in a `<pre>` HTML tag for some reason, which [normally tells the browser to treat the contents like plain text](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre):

```
<pre>&lt;object data="media/Step1.avi" type="video/x-msvideo" width="320" height="256"&gt;
  &lt;param name="src" value="media/Step1.avi"&gt;
  &lt;param name="autoStart" value="0"&gt;
  
&lt;/object&gt;
</pre>
```

I'll have to do some research, since the browser is actually doing what it's supposed to be doing, and "fixing" it could result in other pages breaking.

**Comment by llacb47** [comment]
No, the `<pre>` is for showing the code on the page, the embed code is there normally.

![image](https://user-images.githubusercontent.com/16567977/68445257-5eced180-01a7-11ea-92de-ba81aaffcb47.png)

**Comment by corbindavenport** [comment]
Whoops, you're right. I'll look into this.

**Comment by corbindavenport** [comment]
Looks like NoPlugin was just missing the detection code for the `video/x-ms-wmv` and `video/x-msvideo` types. This fix will be included in the next update.

**Comment by corbindavenport** [comment]
NoPlugin 6.0 is now rolling out with this fix included.

**Comment by llacb47** [comment]
For both MOV examples on the original page `http://personal.psu.edu/staff/d/r/drs18/XHTMLVideo/`, NoPlugin doesn't work properly for me. The video doesn't load and I'm not asked to download it either. There is just a spinner animation in the player.

**Comment by corbindavenport** [comment]
What browser/OS are you using? NoPlugin 6.0 recognizes both MOV embeds for me.

![image](https://user-images.githubusercontent.com/3879063/70109602-65236280-161a-11ea-9ba0-8270cc97b746.png)
![image](https://user-images.githubusercontent.com/3879063/70109618-6fddf780-161a-11ea-9eda-8e7ded838930.png)

**Comment by llacb47** [comment]
Chrome 78 on Windows 10

**Comment by corbindavenport** [comment]
It looks like Chrome is trying to play the video, but only the audio track is compatible, not the video track. You can still download the video by right-clicking it and selecting 'Save as...' (or by clicking the menu button if the controls show up).

![Screenshot from 2019-12-04 17-41-47](https://user-images.githubusercontent.com/3879063/70187994-8d17d200-16bd-11ea-8ee6-6cbacf2dd607.png)
