### ISSUE TITLE
Can't play .wav files

### ISSUE THREAD

**Issue by steven-j-klein** [corbindavenport/noplugin#8]
My environment:
- Version 58.0.3029.81 (64-bit)
- macOS 10.12.4
- QuickTime Player version 10.4 (894.12)

I use Gmail, and I read my email in Chrome.

When some leaves me voicemail, our phone system mails the voicemail to my Gmail as an attached .wav file. (It's encoded using MS-GSM 6.10, 8000 Hz, which is very common for voicemail systems).

I tested this in Safari, and it just works -- I can play the .wav file right in my browser window.  But I need to get it working in Chrome, because our IT staff wants to standardize on Chrome, and uninstall or disable other browsers.

Here's what happens when I try and play that attached file In Chrome. I click the attachment and this flashes on the screen:

![chrome audio player](https://cloud.githubusercontent.com/assets/12419345/25529279/74238066-2bef-11e7-8db2-0cc043f83101.png)

It is immediately replaced by this:

![chrome wav error](https://cloud.githubusercontent.com/assets/12419345/25529306/8090933e-2bef-11e7-9512-f1d7e9dc6db2.png)

I hoped noplugin would fix this, but it hasn't made any difference.  The behavior hasn't changed at all.

**Troubleshooting**
- I verified that noplugin was installed and enabled
- I restarted Chrome
- I downloaded and installed VLC player (since you mention that in your documentation)

None of that helped.

So my current workflow is:

1. Click the attachment
2. Download the file
3. Open my Downloads folder
4. Find and open the file
5. Play it in QuickTime Player. (Or VLC -- that works, too.)
6. Quit the player app
7. Delete the file (to prevent my downloads folder from filling up with old voicemails).

I had hoped that noplugin would end this drugery, but alas, it doesn't seems to have made any difference.

Is noplugin specific to Chrome running in Windows? Is some kind of configuration needed?

Do you have any suggestions for getting this to work?

**Comment by corbindavenport** [comment]
Thanks for the detailed bug report. WAV files should play in the browser just fine, so that's definitely not supposed to happen. I'll do some testing and see if I can identify the problem.

**Comment by corbindavenport** [comment]
I sent myself a .WAV file in Gmail, and it could play fine on Chrome 49 on Mac OS X 10.9.5. The behavior was identical with or without NoPlugin installed, so I don't think this is a problem caused (or can be fixed) by the extension.

If you're still having difficulties, I recommend making a post on the official Chrome Product Forums: https://productforums.google.com/forum/#!forum/chrome
