### ISSUE TITLE
Cant download media player video

### ISSUE THREAD

**Issue by ronen1n** [corbindavenport/noplugin#97]
Im trying to download from this site and I think it's trying to download the wrong file because he calls all the files 3d.wmv and it's not the name of all the files
http://toraland.co.il/allsites/1/Assets/dy/dmain.asp?Masechet=brachot&Page=7

**Comment by corbindavenport** [comment]
It seems like NoPlugin is working as intended, but the web server is missing files. You can see a 404 on [the actual media links](http://toraland.co.il/allsites/1/Assets/dy/3d.wmv).

**Comment by ronen1n** [comment]
Like I said the file name is not 3d.wmv and that's why is giving 404 error
